export const CITY_OPTIONS = [
  {
    id: 'san-francisco-us-ca',
    label: 'San Francisco, California, USA',
    query: 'San Francisco,CA,US',
    longitude: -122.4194,
    latitude: 37.7749,
    zoom: 11,
  },
  {
    id: 'austin-us-tx',
    label: 'Austin, Texas, USA',
    query: 'Austin,TX,US',
    longitude: -97.7431,
    latitude: 30.2672,
    zoom: 10.5,
  },
  {
    id: 'seattle-us-wa',
    label: 'Seattle, Washington, USA',
    query: 'Seattle,WA,US',
    longitude: -122.3321,
    latitude: 47.6062,
    zoom: 10.8,
  },
  {
    id: 'chicago-us-il',
    label: 'Chicago, Illinois, USA',
    query: 'Chicago,IL,US',
    longitude: -87.6298,
    latitude: 41.8781,
    zoom: 10.8,
  },
  {
    id: 'new-york-us-ny',
    label: 'New York City, New York, USA',
    query: 'New York,NY,US',
    longitude: -74.006,
    latitude: 40.7128,
    zoom: 10.8,
  },
  {
    id: 'los-angeles-us-ca',
    label: 'Los Angeles, California, USA',
    query: 'Los Angeles,CA,US',
    longitude: -118.2437,
    latitude: 34.0522,
    zoom: 10.6,
  },
  {
    id: 'san-diego-us-ca',
    label: 'San Diego, California, USA',
    query: 'San Diego,CA,US',
    longitude: -117.1611,
    latitude: 32.7157,
    zoom: 10.8,
  },
  {
    id: 'san-jose-us-ca',
    label: 'San Jose, California, USA',
    query: 'San Jose,CA,US',
    longitude: -121.8863,
    latitude: 37.3382,
    zoom: 10.9,
  },
  {
    id: 'sacramento-us-ca',
    label: 'Sacramento, California, USA',
    query: 'Sacramento,CA,US',
    longitude: -121.4944,
    latitude: 38.5816,
    zoom: 11,
  },
  {
    id: 'phoenix-us-az',
    label: 'Phoenix, Arizona, USA',
    query: 'Phoenix,AZ,US',
    longitude: -112.074,
    latitude: 33.4484,
    zoom: 10.7,
  },
  {
    id: 'las-vegas-us-nv',
    label: 'Las Vegas, Nevada, USA',
    query: 'Las Vegas,NV,US',
    longitude: -115.1398,
    latitude: 36.1699,
    zoom: 10.9,
  },
  {
    id: 'denver-us-co',
    label: 'Denver, Colorado, USA',
    query: 'Denver,CO,US',
    longitude: -104.9903,
    latitude: 39.7392,
    zoom: 10.9,
  },
  {
    id: 'salt-lake-city-us-ut',
    label: 'Salt Lake City, Utah, USA',
    query: 'Salt Lake City,UT,US',
    longitude: -111.891,
    latitude: 40.7608,
    zoom: 11,
  },
  {
    id: 'albuquerque-us-nm',
    label: 'Albuquerque, New Mexico, USA',
    query: 'Albuquerque,NM,US',
    longitude: -106.6504,
    latitude: 35.0844,
    zoom: 10.9,
  },
  {
    id: 'dallas-us-tx',
    label: 'Dallas, Texas, USA',
    query: 'Dallas,TX,US',
    longitude: -96.797,
    latitude: 32.7767,
    zoom: 10.6,
  },
  {
    id: 'houston-us-tx',
    label: 'Houston, Texas, USA',
    query: 'Houston,TX,US',
    longitude: -95.3698,
    latitude: 29.7604,
    zoom: 10.4,
  },
  {
    id: 'san-antonio-us-tx',
    label: 'San Antonio, Texas, USA',
    query: 'San Antonio,TX,US',
    longitude: -98.4936,
    latitude: 29.4241,
    zoom: 10.8,
  },
  {
    id: 'fort-worth-us-tx',
    label: 'Fort Worth, Texas, USA',
    query: 'Fort Worth,TX,US',
    longitude: -97.3308,
    latitude: 32.7555,
    zoom: 10.9,
  },
  {
    id: 'el-paso-us-tx',
    label: 'El Paso, Texas, USA',
    query: 'El Paso,TX,US',
    longitude: -106.485,
    latitude: 31.7619,
    zoom: 11,
  },
  {
    id: 'miami-us-fl',
    label: 'Miami, Florida, USA',
    query: 'Miami,FL,US',
    longitude: -80.1918,
    latitude: 25.7617,
    zoom: 11,
  },
  {
    id: 'orlando-us-fl',
    label: 'Orlando, Florida, USA',
    query: 'Orlando,FL,US',
    longitude: -81.3792,
    latitude: 28.5383,
    zoom: 10.9,
  },
  {
    id: 'tampa-us-fl',
    label: 'Tampa, Florida, USA',
    query: 'Tampa,FL,US',
    longitude: -82.4572,
    latitude: 27.9506,
    zoom: 10.9,
  },
  {
    id: 'jacksonville-us-fl',
    label: 'Jacksonville, Florida, USA',
    query: 'Jacksonville,FL,US',
    longitude: -81.6557,
    latitude: 30.3322,
    zoom: 10.5,
  },
  {
    id: 'atlanta-us-ga',
    label: 'Atlanta, Georgia, USA',
    query: 'Atlanta,GA,US',
    longitude: -84.388,
    latitude: 33.749,
    zoom: 10.8,
  },
  {
    id: 'nashville-us-tn',
    label: 'Nashville, Tennessee, USA',
    query: 'Nashville,TN,US',
    longitude: -86.7816,
    latitude: 36.1627,
    zoom: 10.9,
  },
  {
    id: 'charlotte-us-nc',
    label: 'Charlotte, North Carolina, USA',
    query: 'Charlotte,NC,US',
    longitude: -80.8431,
    latitude: 35.2271,
    zoom: 10.8,
  },
  {
    id: 'raleigh-us-nc',
    label: 'Raleigh, North Carolina, USA',
    query: 'Raleigh,NC,US',
    longitude: -78.6382,
    latitude: 35.7796,
    zoom: 11,
  },
  {
    id: 'washington-us-dc',
    label: 'Washington, District of Columbia, USA',
    query: 'Washington,DC,US',
    longitude: -77.0369,
    latitude: 38.9072,
    zoom: 11,
  },
  {
    id: 'baltimore-us-md',
    label: 'Baltimore, Maryland, USA',
    query: 'Baltimore,MD,US',
    longitude: -76.6122,
    latitude: 39.2904,
    zoom: 11,
  },
  {
    id: 'philadelphia-us-pa',
    label: 'Philadelphia, Pennsylvania, USA',
    query: 'Philadelphia,PA,US',
    longitude: -75.1652,
    latitude: 39.9526,
    zoom: 10.9,
  },
  {
    id: 'pittsburgh-us-pa',
    label: 'Pittsburgh, Pennsylvania, USA',
    query: 'Pittsburgh,PA,US',
    longitude: -79.9959,
    latitude: 40.4406,
    zoom: 11,
  },
  {
    id: 'boston-us-ma',
    label: 'Boston, Massachusetts, USA',
    query: 'Boston,MA,US',
    longitude: -71.0589,
    latitude: 42.3601,
    zoom: 11,
  },
  {
    id: 'detroit-us-mi',
    label: 'Detroit, Michigan, USA',
    query: 'Detroit,MI,US',
    longitude: -83.0458,
    latitude: 42.3314,
    zoom: 10.9,
  },
  {
    id: 'minneapolis-us-mn',
    label: 'Minneapolis, Minnesota, USA',
    query: 'Minneapolis,MN,US',
    longitude: -93.265,
    latitude: 44.9778,
    zoom: 10.8,
  },
  {
    id: 'st-louis-us-mo',
    label: 'St. Louis, Missouri, USA',
    query: 'St Louis,MO,US',
    longitude: -90.1994,
    latitude: 38.627,
    zoom: 10.9,
  },
  {
    id: 'kansas-city-us-mo',
    label: 'Kansas City, Missouri, USA',
    query: 'Kansas City,MO,US',
    longitude: -94.5786,
    latitude: 39.0997,
    zoom: 10.8,
  },
  {
    id: 'new-orleans-us-la',
    label: 'New Orleans, Louisiana, USA',
    query: 'New Orleans,LA,US',
    longitude: -90.0715,
    latitude: 29.9511,
    zoom: 11,
  },
  {
    id: 'columbus-us-oh',
    label: 'Columbus, Ohio, USA',
    query: 'Columbus,OH,US',
    longitude: -82.9988,
    latitude: 39.9612,
    zoom: 10.9,
  },
  {
    id: 'cleveland-us-oh',
    label: 'Cleveland, Ohio, USA',
    query: 'Cleveland,OH,US',
    longitude: -81.6944,
    latitude: 41.4993,
    zoom: 11,
  },
  {
    id: 'cincinnati-us-oh',
    label: 'Cincinnati, Ohio, USA',
    query: 'Cincinnati,OH,US',
    longitude: -84.512,
    latitude: 39.1031,
    zoom: 11,
  },
  {
    id: 'indianapolis-us-in',
    label: 'Indianapolis, Indiana, USA',
    query: 'Indianapolis,IN,US',
    longitude: -86.1581,
    latitude: 39.7684,
    zoom: 10.9,
  },
  {
    id: 'milwaukee-us-wi',
    label: 'Milwaukee, Wisconsin, USA',
    query: 'Milwaukee,WI,US',
    longitude: -87.9065,
    latitude: 43.0389,
    zoom: 11,
  },
  {
    id: 'omaha-us-ne',
    label: 'Omaha, Nebraska, USA',
    query: 'Omaha,NE,US',
    longitude: -95.998,
    latitude: 41.2565,
    zoom: 11,
  },
  {
    id: 'portland-us-or',
    label: 'Portland, Oregon, USA',
    query: 'Portland,OR,US',
    longitude: -122.6765,
    latitude: 45.5231,
    zoom: 10.7,
  },
  {
    id: 'portland-us-me',
    label: 'Portland, Maine, USA',
    query: 'Portland,ME,US',
    longitude: -70.2553,
    latitude: 43.6591,
    zoom: 11.4,
  },
  {
    id: 'boise-us-id',
    label: 'Boise, Idaho, USA',
    query: 'Boise,ID,US',
    longitude: -116.2023,
    latitude: 43.615,
    zoom: 11,
  },
  {
    id: 'anchorage-us-ak',
    label: 'Anchorage, Alaska, USA',
    query: 'Anchorage,AK,US',
    longitude: -149.9003,
    latitude: 61.2181,
    zoom: 10.4,
  },
  {
    id: 'honolulu-us-hi',
    label: 'Honolulu, Hawaii, USA',
    query: 'Honolulu,HI,US',
    longitude: -157.8583,
    latitude: 21.3069,
    zoom: 11,
  },
  {
    id: 'springfield-us-il',
    label: 'Springfield, Illinois, USA',
    query: 'Springfield,IL,US',
    longitude: -89.6501,
    latitude: 39.7817,
    zoom: 11.3,
  },
  {
    id: 'springfield-us-mo',
    label: 'Springfield, Missouri, USA',
    query: 'Springfield,MO,US',
    longitude: -93.2923,
    latitude: 37.2089,
    zoom: 11.1,
  },
  {
    id: 'providence-us-ri',
    label: 'Providence, Rhode Island, USA',
    query: 'Providence,RI,US',
    longitude: -71.4128,
    latitude: 41.824,
    zoom: 11.2,
  },
  {
    id: 'richmond-us-va',
    label: 'Richmond, Virginia, USA',
    query: 'Richmond,VA,US',
    longitude: -77.436,
    latitude: 37.5407,
    zoom: 11,
  },
  {
    id: 'norfolk-us-va',
    label: 'Norfolk, Virginia, USA',
    query: 'Norfolk,VA,US',
    longitude: -76.2859,
    latitude: 36.8508,
    zoom: 11,
  },
  {
    id: 'oklahoma-city-us-ok',
    label: 'Oklahoma City, Oklahoma, USA',
    query: 'Oklahoma City,OK,US',
    longitude: -97.5164,
    latitude: 35.4676,
    zoom: 10.8,
  },
  {
    id: 'tulsa-us-ok',
    label: 'Tulsa, Oklahoma, USA',
    query: 'Tulsa,OK,US',
    longitude: -95.9928,
    latitude: 36.154,
    zoom: 11,
  },
  {
    id: 'memphis-us-tn',
    label: 'Memphis, Tennessee, USA',
    query: 'Memphis,TN,US',
    longitude: -90.049,
    latitude: 35.1495,
    zoom: 10.9,
  },
  {
    id: 'louisville-us-ky',
    label: 'Louisville, Kentucky, USA',
    query: 'Louisville,KY,US',
    longitude: -85.7585,
    latitude: 38.2527,
    zoom: 11,
  },
  {
    id: 'buffalo-us-ny',
    label: 'Buffalo, New York, USA',
    query: 'Buffalo,NY,US',
    longitude: -78.8784,
    latitude: 42.8864,
    zoom: 11,
  },
  {
    id: 'rochester-us-ny',
    label: 'Rochester, New York, USA',
    query: 'Rochester,NY,US',
    longitude: -77.6109,
    latitude: 43.1566,
    zoom: 11,
  },
  {
    id: 'albany-us-ny',
    label: 'Albany, New York, USA',
    query: 'Albany,NY,US',
    longitude: -73.7562,
    latitude: 42.6526,
    zoom: 11.2,
  },
  {
    id: 'newark-us-nj',
    label: 'Newark, New Jersey, USA',
    query: 'Newark,NJ,US',
    longitude: -74.1724,
    latitude: 40.7357,
    zoom: 11.2,
  },
  {
    id: 'jersey-city-us-nj',
    label: 'Jersey City, New Jersey, USA',
    query: 'Jersey City,NJ,US',
    longitude: -74.0776,
    latitude: 40.7282,
    zoom: 11.2,
  },
  {
    id: 'madison-us-wi',
    label: 'Madison, Wisconsin, USA',
    query: 'Madison,WI,US',
    longitude: -89.4012,
    latitude: 43.0731,
    zoom: 11.2,
  },
  {
    id: 'des-moines-us-ia',
    label: 'Des Moines, Iowa, USA',
    query: 'Des Moines,IA,US',
    longitude: -93.625,
    latitude: 41.5868,
    zoom: 11.1,
  },
];

export const DEFAULT_CITY = CITY_OPTIONS[0];
